---
title: "Raport drogowy"
output: 
  powerpoint_presentation: default
#  pdf_document: default
#  html_document: default
#knit: (function(inputFile, encoding) {
#  rmarkdown::render(inputFile, encoding = encoding,
#  output_dir = "odcinek13", output_format = "all") })  
classoption: landscape  
date: "2023-10-16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(tidyverse)
library(patchwork)
#library(tinytex)

setwd("c:/users/tomek/dane")

ruch <- read.csv("scpr2022.csv", sep = ";" ) %>%
  mutate(data = dmy(DATA), auta = SDRD, stacja = STACJA) %>%
  select(stacja, data, auta)

```


```{r, results='asis', fig.width=12, fig.height=6}

nrstacji <- 2012
for(nrstacji in unique(ruch$stacja) ) {  

  cat("  \n# Stacja pomiarowa numer ",  nrstacji, "\n")
  
  p1 <- ruch %>%
    filter(stacja == nrstacji) %>%
    ggplot(aes(x=data, y=auta)) +
    geom_line() +
    geom_smooth(method=lm) +
    xlab("Data") +
    ylab("Liczba samochodów") +
    theme_minimal() 

  p2 <- ruch %>%
    filter(stacja == nrstacji) %>%
    group_by( dzien_tyg = wday(data, label=TRUE) ) %>%
    summarise( sredni_ruch = mean(auta) ) %>%
    ggplot(aes(x=dzien_tyg, y=sredni_ruch, fill=sredni_ruch)) +
    geom_col() +
    xlab("Dni tygodnia") +
    ylab("Liczba samochodów") +
    theme_minimal() +
    scale_fill_viridis_c()

  print(p1 + p2)
  
  cat("  \n")

}
```


